

url    : "sapiencepath.github.io"
baseurl: "" 

title      : Sapience Path
email      : contact.us@sapiencepath.com #this is also the email contact forms will go to
description: "Strives to Propel Digitization"

logo:     #optional, defaults to site title
  path: assets\img\logo-03.jpg
  height: 60 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/moqyewzq"