

url    : "sapiencepath.github.io" 
baseurl: "" 
title      : Sapience Path
email      : contact.us@sapiencepath.com 
description: "Strives to Propel Digitization"

logo:    
  path: assets\img\logo-03.jpg
  height: 60 

locale: "en-US" 

analytics:
  google: UA-178493960-1
collections:
  portfolio:

markdown: kramdown
# Uncomment following line to use Formspree form ID based URL instead of email based URL
#Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/moqyewzq"
